---
- hosts: myservers
  vars:
      package1: "httpd"
  tasks:
    - name: Installing package1
      yum:
        name: git
        state: latest
      become: true
    - name: Installing httpd
      yum:
        name: "{{ package1 }}"
        state: latest
      become: true
    - name: Start package1
      systemd:
        name: "{{ package1 }}"
        state: started 
      become: true
